In [1]:
fam = [1.72,1.77,1.68,1.83,1.87]
print(fam)

[1.72, 1.77, 1.68, 1.83, 1.87]


In [2]:
max(fam)

1.87

In [3]:
round(1.68) # round to closest number

2

In [4]:
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [5]:
round(1.68,1)

1.7

In [6]:
len(fam)

5

In [7]:
#Python objects come with built in methods
fam.index(1.77) #index of the element

1

In [8]:
#Count the number of times an element appears in the list
fam.count(1.77)

1

In [9]:
string = 'liz'
print(string)

liz


In [10]:
string.capitalize()

'Liz'

In [11]:
string.replace('z','sa')

'lisa'

In [12]:
#replace method is not available on lists
fam.append("a")
print(fam)

[1.72, 1.77, 1.68, 1.83, 1.87, 'a']


In [13]:
type(fam)

list

In [15]:
#Packages specify functions, methods, types

In [19]:
import numpy as np

In [23]:
print(np.__version__)

1.13.3


In [24]:
np.array([1,2,3])

array([1, 2, 3])

In [26]:
from numpy import array

In [27]:
array([1,2,3])

array([1, 2, 3])

In [28]:
import numpy as np
np.array(fam)

array(['1.72', '1.77', '1.68', '1.83', '1.87', 'a'],
      dtype='<U32')

In [29]:
#Numpy array is an alternative to Python List and it also enables calculations over entire arrays


In [30]:
import numpy as np
height = np.array([1.73,1.65,1.82,1.77])
weight = np.array([68.7,64.6,73.7,81.2])

In [32]:
bmi = weight / height ** 2
print(bmi)

[ 22.95432524  23.728191    22.24972829  25.91847809]


In [34]:
#Numpy array can contain only one type. So if you insert different data types in an array they will converted to strings
np.array([1.7,'Hello'])

array(['1.7', 'Hello'],
      dtype='<U32')

In [35]:
#It also comes with certain methods . 
# + operator will lead to element-wise sum of the arrays.
#Lists are concatenated when we use + operator

height + height

array([ 3.46,  3.3 ,  3.64,  3.54])

In [36]:
bmi[0]
bmi  > 23.5

array([False,  True, False,  True], dtype=bool)

In [37]:
bmi[bmi > 23.5]

array([ 23.728191  ,  25.91847809])

In [39]:
type(height) # n-dimesional array


numpy.ndarray

In [42]:
#height and bmi are one - dimensional arrays
#Let's make a two dimesional array

height_weight = np.array([[1.73,1.65,1.82,1.77],[68.7,64.6,73.7,81.2]])

In [43]:
print(height_weight)

[[  1.73   1.65   1.82   1.77]
 [ 68.7   64.6   73.7   81.2 ]]


In [44]:
height_weight = np.array([height, weight])

In [45]:
height_weight

array([[  1.73,   1.65,   1.82,   1.77],
       [ 68.7 ,  64.6 ,  73.7 ,  81.2 ]])

In [46]:
#shape is an attribute of an array print m x n
#m represents the number of rows and n represents the number of columns
height_weight.shape

(2, 4)

In [47]:
m , n = height_weight.shape

In [48]:
print(m,n)

2 4


In [56]:
#Subsetting .
#To access the second element of the second row, we do something like this

height_weight[1][1]

64.599999999999994

In [58]:
num = height_weight[1][1]
print(num) # Need to find out the reason for this

64.6


In [59]:
height_weight[1,1]

64.599999999999994

In [60]:
height_weight[:,1:3] # A 2d array with 2 rows and 2 colums

array([[  1.6,   1.8],
       [ 64.6,  73.7]])

In [61]:
height_weight[1,:] #Weights

array([ 68.7,  64.6,  73.7,  81.2])

In [62]:
np.mean(height_weight[0,:]) #Average of all heights

1.7425000000000002

In [ ]:
#Similarly median and std (standard deviation) method exists


In [ ]:
#Need to find out why [57] is happening .Taking this as an assignment